name: jaspr_html_convert
description: Convert raw HTML to Jaspr components.
version: 1.0.0
repository: https://github.com/tazatechnology/jaspr_html_convert

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  html: ^0.15.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  import_sorter: ^4.6.0
  dart_style: ^2.3.6
  path: ^1.9.0
  
import_sorter:
  comments: false