name: jaspr_html_convert
description: Convert raw HTML to Jaspr components.
version: 1.0.0
repository: https://github.com/tazatechnology/jaspr_html_convert

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Resolves conflict for with jaspr_builder and dart_style
  # dart_style: 2.3.2
  html: ^0.15.4
  recase: ^4.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  import_sorter: ^4.6.0
  
import_sorter:
  comments: false