name: CI
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Test Package
        run: dart pub get && make test

      - name: Build Application
        working-directory: ./example
        run: |
          dart pub global activate jaspr_cli
          jaspr build